export { default as Login } from "./auth/Login"
export { default as Register } from "./auth/Register"
export { default as ResetPassword } from "./auth/ResetPassword"
export { default as DashBoard } from "./dashboard/DashBoard"
export { default as AddTicket } from "./new-ticket/AddTicket"
export { default as TicketList } from "./ticket-list/TicketList"
export { default as Ticket } from "./ticket/Ticket"
